version: '3'
services:
  ubuntu:
    container_name: sysdev
    build: ./docker
    tty: true
    volumes:
      - ./:/src
    cap_add:
      - CAP_SYS_ADMIN
    security_opt:
      - seccomp:unconfined
